version: '3.8'

services:
  postgres:
    image: postgres:alpine3.18
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=itk
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local