server:
  port: 8080

spring:
  application:
    name: itk-practical-tasks
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/itk
    username: root
    password: root
    hikari:
      validation-timeout: 30000