server:
  port: 8080
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: root123
    key-store-type: PKCS12
    key-alias: myapp
    enabled: true
  http:
    enabled: false

spring:
  application:
    name: itk-practical-tasks
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/itk
    username: root
    password: root
    hikari:
      validation-timeout: 30000


app:
  secret: hncd435l9xmed2334jnrexcvbn6450293845ndwer43hdzmafp73h5m9d70fjmc8sw3