server:
  port: 8080

spring:
  application:
    name: itk-practical-tasks
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/itk
    username: root
    password: root
    hikari:
      validation-timeout: 30000


app:
  secret: hncd435l9xmed2334jnrexcvbn6450293845ndwer43hdzmafp73h5m9d70fjmc8sw3